       IDENTIFICATION DIVISION.
       PROGRAM-ID. CBLHJB02.
	   AUTHOR. HARRISON BIRKNER.

       ENVIRONMENT DIVISION.
		   SELECT BOAT-INPUT
			   ASSIGN TO 'C:\COBOLWI19\CBLBOAT1.DAT'
				   ORGANIZATION IS LINE SEQUENTIAL.

		   SELECT PRTOUT
		       ASSIGN TO 'C:\COBOLWI19\BOATRPT1.PRT'
				   ORGANIZATION IS RECORD SEQUENTIAL.
       DATA DIVISION.
	   FILE SECTION.
	   FD BOAT-INPUT
	   LABEL RECORD IS STANDARD
	   DATA RECORD IS I-REC
	   RECORD CONTAINS 42 CHARACTERS.

	   01 I-REC.

	   FD PRTOUT
	   LABEL RECORD IS OMITTED
	   DATA RECORD IS PRTLINE
	   RECORD CONTAINS 132 CHARACTERS
	   LINAGE IS 60 WITH FOOTING AT 56.

	   01 PRTLINE                         PIC X(132).

       WORKING-STORAGE SECTION.

       PROCEDURE DIVISION.

           STOP RUN.
           
       END PROGRAM CBLHJB02.